//! macOS reliable paste.
//!
//! Publishes the transcript with `declareTypes:owner:`, which puts a *promise*
//! on the general pasteboard instead of data. When any consumer actually
//! requests the text, AppKit calls `pasteboard:provideDataForType:` on our
//! owner object. The callback does not identify the reader, so it is diagnostic
//! only: it never governs timing, auto-submit, or restoration.
//!
//! Threading: publishing and chord injection happen on the calling (main)
//! thread, because promised pasteboard data is serviced by AppKit on the main
//! run loop. The (potentially seconds-long) wait runs on a worker thread; the
//! guarded settlement is dispatched back to the main thread.

use std::sync::{Arc, Mutex};
use std::thread;
use std::time::{Duration, Instant};

use log::{error, info};
use objc2::rc::Retained;
use objc2::{define_class, msg_send, AnyThread, DefinedClass};
use objc2_app_kit::{NSPasteboard, NSPasteboardTypeString};
use objc2_foundation::{NSArray, NSInteger, NSObject, NSString};
use tauri::AppHandle;

use super::{evaluate, TxState, WaitDecision};
use crate::clipboard::{
    frontmost_target, send_paste_if_target_unchanged, send_return_if_target_unchanged,
    FrontmostTarget,
};
use crate::settings::{AutoSubmitKey, ClipboardHandling};

/// Concealment marker types declared alongside the text so that well-behaved
/// third-party clipboard managers (Maccy, Paste, ...) skip the transcript.
/// These are conventions, not a security boundary.
const CONCEALMENT_TYPES: [&str; 3] = [
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
];
const TEXT_PASTEBOARD_TYPE: &str = "public.utf8-plain-text";

pub struct ProviderIvars {
    state: Arc<Mutex<TxState>>,
    text: String,
}

define_class!(
    // SAFETY: NSObject has no subclassing requirements and the ivars are
    // plain Rust values guarded by a Mutex.
    #[unsafe(super(NSObject))]
    #[name = "MurmurPasteProvider"]
    #[ivars = ProviderIvars]
    pub struct MurmurPasteProvider;

    impl MurmurPasteProvider {
        // NSPasteboardOwner informal protocol: the pasteboard is asking for the
        // promised data — our receipt that a consumer read the clipboard.
        #[unsafe(method(pasteboard:provideDataForType:))]
        fn pasteboard_provide_data_for_type(&self, pasteboard: &NSPasteboard, data_type: &NSString) {
            let ivars = self.ivars();
            // SAFETY: NSPasteboardTypeString is a read-only framework static.
            let is_text = unsafe { data_type.isEqualToString(NSPasteboardTypeString) };
            // Only a text read counts as a receipt: a request for one of the
            // concealment marker types is a clipboard manager inspecting the
            // markers, not the paste target reading the transcript.
            if is_text {
                if let Ok(mut state) = ivars.state.lock() {
                    state.record_receipt(Instant::now());
                }
            }
            let payload = if is_text {
                NSString::from_str(&ivars.text)
            } else {
                // Concealment marker types are never handed out.
                NSString::from_str("")
            };
            let _ = pasteboard.setString_forType(&payload, data_type);
        }

        #[unsafe(method(pasteboardChangedOwner:))]
        fn pasteboard_changed_owner(&self, _pasteboard: &NSPasteboard) {
            if let Ok(mut state) = self.ivars().state.lock() {
                state.ownership_lost = true;
            }
        }
    }
);

impl MurmurPasteProvider {
    fn new(state: Arc<Mutex<TxState>>, text: String) -> Retained<Self> {
        let this = Self::alloc().set_ivars(ProviderIvars { state, text });
        unsafe { msg_send![super(this), init] }
    }
}

struct MacPending {
    state: Arc<Mutex<TxState>>,
    change_count: NSInteger,
    provider: Option<Retained<MurmurPasteProvider>>,
    /// ClipboardHandling::CopyToClipboard settles by materializing every
    /// promised type so the transcript outlives the provider. Otherwise Murmur
    /// clears its promise after settlement.
    preserve_transcript: bool,
    /// The transcript, for `preserve_transcript` materialization at settle time.
    transcript: String,
    settled: bool,
}

/// The transaction currently holding the clipboard, if any. A new paste
/// settles it before publishing its own promise (see `flush_pending`).
static PENDING: Mutex<Option<Arc<Mutex<MacPending>>>> = Mutex::new(None);

/// Materializes every type promised through `declareTypes:owner:` before the
/// provider is released. Must run on the main thread.
fn materialize_promised_data(pasteboard: &NSPasteboard, transcript: &str) -> bool {
    let payload = NSString::from_str(transcript);
    let text_type = NSString::from_str(TEXT_PASTEBOARD_TYPE);
    if !pasteboard.setString_forType(&payload, &text_type) {
        return false;
    }

    let empty = NSString::from_str("");
    for marker in CONCEALMENT_TYPES {
        let marker_type = NSString::from_str(marker);
        if !pasteboard.setString_forType(&empty, &marker_type) {
            return false;
        }
    }
    true
}

fn finish_settlement(pending: &mut MacPending) {
    pending.settled = true;
    // Every promised type has been materialized, erased, or replaced by an
    // external owner, so the provider no longer needs to stay alive.
    pending.provider = None;
}

/// Settles a transaction exactly once by keeping or clearing the transcript.
/// Earlier clipboard values are never restored. Auto-submit happens only in
/// the targeted event path and never depends on an AppKit read callback.
/// Must run on the main thread.
fn settle(pending: &Arc<Mutex<MacPending>>) {
    let mut p = match pending.lock() {
        Ok(p) => p,
        Err(_) => return,
    };
    if p.settled {
        return;
    }
    let (ownership_lost, injection_failed) = match p.state.lock() {
        Ok(st) => (st.ownership_lost, st.injection_failed),
        Err(_) => (true, false),
    };

    let still_ours =
        !ownership_lost && NSPasteboard::generalPasteboard().changeCount() == p.change_count;

    // If the chord never reached the target, retaining the transcript is the
    // only non-destructive outcome. The caller's clear-after-paste preference
    // applies only after a paste was actually injected.
    match decide_settlement(still_ours, p.preserve_transcript || injection_failed) {
        ClipboardSettlement::LeaveUntouched => {
            info!("[reliable-paste] clipboard changed externally; leaving it untouched");
        }
        ClipboardSettlement::KeepTranscript => {
            if NSPasteboard::generalPasteboard().changeCount() != p.change_count {
                info!("[reliable-paste] clipboard changed before materialization; leaving it untouched");
                finish_settlement(&mut p);
                return;
            }
            // Fill every declared type in place. Unlike arboard::set_text,
            // this does not clear the promise before attempting the write.
            if materialize_promised_data(&NSPasteboard::generalPasteboard(), &p.transcript) {
                info!("[reliable-paste] materialized transcript for clipboard recovery");
            } else {
                info!("[reliable-paste] clipboard changed during materialization; leaving it untouched");
            }
        }
        ClipboardSettlement::ClearClipboard => {
            let pasteboard = NSPasteboard::generalPasteboard();
            if pasteboard.changeCount() != p.change_count {
                info!("[reliable-paste] clipboard changed before cleanup; leaving it untouched");
                finish_settlement(&mut p);
                return;
            }
            // Replacing our promised values in place avoids the check-then-clear
            // race: setString fails if another process takes ownership first.
            if materialize_promised_data(&pasteboard, "") {
                info!("[reliable-paste] erased transcript without restoring prior clipboard data");
            } else {
                info!("[reliable-paste] clipboard changed during cleanup; leaving it untouched");
            }
        }
    }

    finish_settlement(&mut p);
}

#[derive(Debug, PartialEq, Eq)]
enum ClipboardSettlement {
    ClearClipboard,
    KeepTranscript,
    LeaveUntouched,
}

fn decide_settlement(still_ours: bool, preserve_transcript: bool) -> ClipboardSettlement {
    if !still_ours {
        ClipboardSettlement::LeaveUntouched
    } else if preserve_transcript {
        ClipboardSettlement::KeepTranscript
    } else {
        ClipboardSettlement::ClearClipboard
    }
}

/// If a previous transaction is still holding the clipboard, settle it before
/// publishing a new promise.
fn flush_pending() {
    let previous = match PENDING.lock() {
        Ok(mut slot) => slot.take(),
        Err(_) => None,
    };
    if let Some(previous) = previous {
        settle(&previous);
    }
}

fn same_pending(
    current: Option<&Arc<Mutex<MacPending>>>,
    candidate: &Arc<Mutex<MacPending>>,
) -> bool {
    current
        .map(|pending| Arc::ptr_eq(pending, candidate))
        .unwrap_or(false)
}

fn is_current_pending(candidate: &Arc<Mutex<MacPending>>) -> bool {
    PENDING
        .lock()
        .map(|slot| same_pending(slot.as_ref(), candidate))
        .unwrap_or(false)
}

fn spawn_waiter(
    pending: Arc<Mutex<MacPending>>,
    app_handle: AppHandle,
    auto_submit: Option<(AutoSubmitKey, FrontmostTarget)>,
) {
    thread::spawn(move || {
        if let Some((auto_submit_key, target)) = auto_submit {
            // Keep AppKit's main run loop free to fulfill the promised
            // pasteboard data before submitting the target form.
            thread::sleep(Duration::from_millis(50));
            let pending_for_submit = pending.clone();
            if let Err(error) = app_handle.run_on_main_thread(move || {
                // A newer paste may have replaced this transaction while the
                // delay elapsed. Focus identity alone cannot detect that when
                // both pastes target the same application.
                if !is_current_pending(&pending_for_submit) {
                    info!("[reliable-paste] skipping auto-submit for superseded transaction");
                    return;
                }
                if let Err(error) =
                    send_return_if_target_unchanged(auto_submit_key, Some(target)).map(|_| ())
                {
                    error!("[reliable-paste] paste succeeded, but auto-submit failed: {error}");
                }
            }) {
                error!("[reliable-paste] failed to queue auto-submit on main thread: {error}");
            }
        }

        let outcome = loop {
            thread::sleep(Duration::from_millis(15));
            let (decision, state_snapshot) = {
                let p = match pending.lock() {
                    Ok(p) => p,
                    Err(_) => return,
                };
                if p.settled {
                    // A newer paste settled this transaction already.
                    return;
                }
                let result = match p.state.lock() {
                    Ok(st) => {
                        let now = Instant::now();
                        let snapshot = (st.ownership_lost, st.injection_failed, st.logged_receipt);
                        (evaluate(&st, now), snapshot)
                    }
                    Err(_) => return,
                };
                result
            };
            if let WaitDecision::Finish = decision {
                break state_snapshot;
            }
        };

        let (ownership_lost, injection_failed, read_observed) = outcome;
        if ownership_lost {
            info!("[reliable-paste] settling: clipboard ownership lost");
        } else if injection_failed {
            info!("[reliable-paste] settling early after chord injection failure");
        } else if read_observed {
            info!("[reliable-paste] settling after bounded lifetime; read observed");
        } else {
            info!("[reliable-paste] settling after bounded lifetime; no read observed");
        }

        let pending_for_finish = pending.clone();
        let _ = app_handle.run_on_main_thread(move || {
            settle(&pending_for_finish);
            if let Ok(mut slot) = PENDING.lock() {
                if same_pending(slot.as_ref(), &pending) {
                    *slot = None;
                }
            }
        });
    });
}

pub(super) fn run(
    text: &str,
    app_handle: &AppHandle,
    auto_submit: bool,
    auto_submit_key: AutoSubmitKey,
    clipboard_handling: ClipboardHandling,
) -> Result<(), String> {
    let target: FrontmostTarget = frontmost_target().ok_or("No stable frontmost paste target")?;
    // Settle any previous transaction before publishing the next promise.
    flush_pending();

    let state = Arc::new(Mutex::new(TxState::new()));
    let provider = MurmurPasteProvider::new(state.clone(), text.to_string());
    let pasteboard = NSPasteboard::generalPasteboard();

    let mut types: Vec<Retained<NSString>> = Vec::with_capacity(1 + CONCEALMENT_TYPES.len());
    types.push(NSString::from_str(TEXT_PASTEBOARD_TYPE));
    for t in CONCEALMENT_TYPES {
        types.push(NSString::from_str(t));
    }
    let types = NSArray::from_retained_slice(&types);

    // declareTypes:owner: clears the pasteboard and puts our promise on it;
    // the return value is the new changeCount.
    let change_count: NSInteger =
        unsafe { msg_send![&*pasteboard, declareTypes: &*types, owner: &*provider] };
    if change_count <= 0 {
        return Err("declareTypes:owner: failed".to_string());
    }
    info!("[reliable-paste] published transcript as lazy promise (changeCount {change_count})");

    // Mark injection *before* sending: enigo holds the chord for ~100ms and a
    // fast target may legitimately read while the chord is still held.
    if let Ok(mut st) = state.lock() {
        st.injected_at = Some(Instant::now());
    }
    let paste_injected = match send_paste_if_target_unchanged(Some(target.clone())) {
        Ok(true) => {
            info!("[reliable-paste] Cmd+V sent");
            true
        }
        Ok(false) => {
            if let Ok(mut st) = state.lock() {
                st.injection_failed = true;
            }
            info!("[reliable-paste] target changed before Cmd+V; paste skipped");
            false
        }
        Err(e) => {
            // Keep the transaction alive long enough to replace the promise
            // with plain transcript text. A failed chord never authorizes
            // restoration of the previous clipboard.
            if let Ok(mut st) = state.lock() {
                st.injection_failed = true;
            }
            error!("[reliable-paste] failed to send paste chord: {e}");
            false
        }
    };

    let pending = Arc::new(Mutex::new(MacPending {
        state,
        change_count,
        provider: Some(provider),
        preserve_transcript: clipboard_handling == ClipboardHandling::CopyToClipboard,
        transcript: text.to_string(),
        settled: false,
    }));
    if let Ok(mut slot) = PENDING.lock() {
        *slot = Some(pending.clone());
    }
    let auto_submit = (paste_injected && auto_submit).then_some((auto_submit_key, target));
    spawn_waiter(pending, app_handle.clone(), auto_submit);

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn never_restores_prior_clipboard_data() {
        assert_eq!(
            decide_settlement(true, false),
            ClipboardSettlement::ClearClipboard
        );
        assert_eq!(
            decide_settlement(false, false),
            ClipboardSettlement::LeaveUntouched
        );
    }

    #[test]
    fn copy_to_clipboard_always_keeps_transcript() {
        assert_eq!(
            decide_settlement(true, true),
            ClipboardSettlement::KeepTranscript
        );
    }

    #[test]
    fn failed_injection_keeps_transcript_for_recovery() {
        let preserve_transcript = false;
        let injection_failed = true;
        assert_eq!(
            decide_settlement(true, preserve_transcript || injection_failed),
            ClipboardSettlement::KeepTranscript
        );
    }

    #[test]
    fn auto_submit_guard_accepts_only_the_current_transaction() {
        fn pending() -> Arc<Mutex<MacPending>> {
            Arc::new(Mutex::new(MacPending {
                state: Arc::new(Mutex::new(TxState::new())),
                change_count: 0,
                provider: None,
                preserve_transcript: false,
                transcript: String::new(),
                settled: false,
            }))
        }

        let current = pending();
        let superseded = pending();

        assert!(same_pending(Some(&current), &current));
        assert!(!same_pending(Some(&current), &superseded));
        assert!(!same_pending(None, &current));
    }
}
