//! macOS reliable paste.
//!
//! Publishes the transcript with `declareTypes:owner:`, which puts a *promise*
//! on the general pasteboard instead of data. When any consumer actually
//! requests the text, AppKit calls `pasteboard:provideDataForType:` on our
//! owner object. The callback does not identify the reader, so it is diagnostic
//! only: it never governs timing, auto-submit, or restoration.
//!
//! Threading: publishing and chord injection happen on the calling (main)
//! thread, because promised pasteboard data is serviced by AppKit on the main
//! run loop. The (potentially seconds-long) wait runs on a worker thread; the
//! guarded settlement is dispatched back to the main thread.

use std::sync::{Arc, Mutex};
use std::thread;
use std::time::{Duration, Instant};

use log::{error, info};
use objc2::rc::Retained;
use objc2::{define_class, msg_send, AnyThread, DefinedClass};
use objc2_app_kit::{NSPasteboard, NSPasteboardTypeString};
use objc2_foundation::{NSArray, NSInteger, NSObject, NSString};
use tauri::AppHandle;
use tauri_plugin_clipboard_manager::ClipboardExt;

use super::{evaluate, TxState, WaitDecision};
use crate::clipboard::{
    frontmost_target, send_paste_if_target_unchanged, send_return_if_target_unchanged,
    FrontmostTarget,
};
use crate::settings::{AutoSubmitKey, ClipboardHandling};

/// Concealment marker types declared alongside the text so that well-behaved
/// third-party clipboard managers (Maccy, Paste, ...) skip the transcript.
/// These are conventions, not a security boundary.
const CONCEALMENT_TYPES: [&str; 3] = [
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
];

pub struct ProviderIvars {
    state: Arc<Mutex<TxState>>,
    text: String,
}

define_class!(
    // SAFETY: NSObject has no subclassing requirements and the ivars are
    // plain Rust values guarded by a Mutex.
    #[unsafe(super(NSObject))]
    #[name = "MurmurPasteProvider"]
    #[ivars = ProviderIvars]
    pub struct MurmurPasteProvider;

    impl MurmurPasteProvider {
        // NSPasteboardOwner informal protocol: the pasteboard is asking for the
        // promised data — our receipt that a consumer read the clipboard.
        #[unsafe(method(pasteboard:provideDataForType:))]
        fn pasteboard_provide_data_for_type(&self, pasteboard: &NSPasteboard, data_type: &NSString) {
            let ivars = self.ivars();
            // SAFETY: NSPasteboardTypeString is a read-only framework static.
            let is_text = unsafe { data_type.isEqualToString(NSPasteboardTypeString) };
            // Only a text read counts as a receipt: a request for one of the
            // concealment marker types is a clipboard manager inspecting the
            // markers, not the paste target reading the transcript.
            if is_text {
                if let Ok(mut state) = ivars.state.lock() {
                    state.record_receipt(Instant::now());
                }
            }
            let payload = if is_text {
                NSString::from_str(&ivars.text)
            } else {
                // Concealment marker types are never handed out.
                NSString::from_str("")
            };
            let _ = pasteboard.setString_forType(&payload, data_type);
        }

        #[unsafe(method(pasteboardChangedOwner:))]
        fn pasteboard_changed_owner(&self, _pasteboard: &NSPasteboard) {
            if let Ok(mut state) = self.ivars().state.lock() {
                state.ownership_lost = true;
            }
        }
    }
);

impl MurmurPasteProvider {
    fn new(state: Arc<Mutex<TxState>>, text: String) -> Retained<Self> {
        let this = Self::alloc().set_ivars(ProviderIvars { state, text });
        unsafe { msg_send![super(this), init] }
    }
}

struct MacPending {
    state: Arc<Mutex<TxState>>,
    change_count: NSInteger,
    provider: Option<Retained<MurmurPasteProvider>>,
    /// ClipboardHandling::CopyToClipboard settles by re-writing the transcript
    /// as plain text, so clipboard managers record it and it outlives the
    /// promise. Otherwise Murmur clears its promise after settlement.
    preserve_transcript: bool,
    /// The transcript, for the `preserve_transcript` re-write at settle time.
    transcript: String,
    settled: bool,
}

/// The transaction currently holding the clipboard, if any. A new paste
/// settles it before publishing its own promise (see `flush_pending`).
static PENDING: Mutex<Option<Arc<Mutex<MacPending>>>> = Mutex::new(None);

/// Settles a transaction exactly once by keeping or clearing the transcript.
/// Earlier clipboard values are never restored. Auto-submit happens only in
/// the targeted event path and never depends on an AppKit read callback.
/// Must run on the main thread.
fn settle(pending: &Arc<Mutex<MacPending>>, app_handle: &AppHandle) {
    let mut p = match pending.lock() {
        Ok(p) => p,
        Err(_) => return,
    };
    if p.settled {
        return;
    }
    p.settled = true;

    let (ownership_lost, injection_failed) = match p.state.lock() {
        Ok(st) => (st.ownership_lost, st.injection_failed),
        Err(_) => (true, false),
    };

    let still_ours =
        !ownership_lost && NSPasteboard::generalPasteboard().changeCount() == p.change_count;

    // If the chord never reached the target, retaining the transcript is the
    // only non-destructive outcome. The caller's clear-after-paste preference
    // applies only after a paste was actually injected.
    match decide_settlement(still_ours, p.preserve_transcript || injection_failed) {
        ClipboardSettlement::LeaveUntouched => {
            info!("[reliable-paste] clipboard changed externally; leaving it untouched");
        }
        ClipboardSettlement::KeepTranscript => {
            if NSPasteboard::generalPasteboard().changeCount() != p.change_count {
                info!("[reliable-paste] clipboard changed before materialization; leaving it untouched");
                p.provider = None;
                return;
            }
            // The user asked for the transcript to stay on the clipboard:
            // replace the concealed promise with plain text.
            let _ = app_handle.clipboard().write_text(&p.transcript);
            info!("[reliable-paste] left transcript on clipboard as plain text");
        }
        ClipboardSettlement::ClearClipboard => {
            if NSPasteboard::generalPasteboard().changeCount() != p.change_count {
                info!("[reliable-paste] clipboard changed before cleanup; leaving it untouched");
                p.provider = None;
                return;
            }
            let _ = app_handle.clipboard().clear();
            info!("[reliable-paste] cleared transcript without restoring prior clipboard data");
        }
    }

    // Release the owner; any outstanding promise dies with the pasteboard
    // contents we just replaced (or with the external change).
    p.provider = None;
}

#[derive(Debug, PartialEq, Eq)]
enum ClipboardSettlement {
    ClearClipboard,
    KeepTranscript,
    LeaveUntouched,
}

fn decide_settlement(still_ours: bool, preserve_transcript: bool) -> ClipboardSettlement {
    if !still_ours {
        ClipboardSettlement::LeaveUntouched
    } else if preserve_transcript {
        ClipboardSettlement::KeepTranscript
    } else {
        ClipboardSettlement::ClearClipboard
    }
}

/// If a previous transaction is still holding the clipboard, settle it before
/// publishing a new promise.
fn flush_pending(app_handle: &AppHandle) {
    let previous = match PENDING.lock() {
        Ok(mut slot) => slot.take(),
        Err(_) => None,
    };
    if let Some(previous) = previous {
        settle(&previous, app_handle);
    }
}

fn spawn_waiter(pending: Arc<Mutex<MacPending>>, app_handle: AppHandle) {
    thread::spawn(move || {
        let outcome = loop {
            thread::sleep(Duration::from_millis(15));
            let (decision, state_snapshot) = {
                let p = match pending.lock() {
                    Ok(p) => p,
                    Err(_) => return,
                };
                if p.settled {
                    // A newer paste settled this transaction already.
                    return;
                }
                let result = match p.state.lock() {
                    Ok(st) => {
                        let now = Instant::now();
                        let snapshot = (st.ownership_lost, st.injection_failed, st.logged_receipt);
                        (evaluate(&st, now), snapshot)
                    }
                    Err(_) => return,
                };
                result
            };
            if let WaitDecision::Finish = decision {
                break state_snapshot;
            }
        };

        let (ownership_lost, injection_failed, read_observed) = outcome;
        if ownership_lost {
            info!("[reliable-paste] settling: clipboard ownership lost");
        } else if injection_failed {
            info!("[reliable-paste] settling early after chord injection failure");
        } else if read_observed {
            info!("[reliable-paste] settling after bounded lifetime; read observed");
        } else {
            info!("[reliable-paste] settling after bounded lifetime; no read observed");
        }

        let pending_for_finish = pending.clone();
        let app_for_finish = app_handle.clone();
        let _ = app_handle.run_on_main_thread(move || {
            settle(&pending_for_finish, &app_for_finish);
            if let Ok(mut slot) = PENDING.lock() {
                let is_us = slot
                    .as_ref()
                    .map(|current| Arc::ptr_eq(current, &pending))
                    .unwrap_or(false);
                if is_us {
                    *slot = None;
                }
            }
        });
    });
}

pub(super) fn run(
    text: &str,
    app_handle: &AppHandle,
    auto_submit: bool,
    auto_submit_key: AutoSubmitKey,
    clipboard_handling: ClipboardHandling,
) -> Result<(), String> {
    let target: FrontmostTarget = frontmost_target().ok_or("No stable frontmost paste target")?;
    // Settle any previous transaction before publishing the next promise.
    flush_pending(app_handle);

    let state = Arc::new(Mutex::new(TxState::new()));
    let provider = MurmurPasteProvider::new(state.clone(), text.to_string());
    let pasteboard = NSPasteboard::generalPasteboard();

    let mut types: Vec<Retained<NSString>> = Vec::with_capacity(1 + CONCEALMENT_TYPES.len());
    types.push(NSString::from_str("public.utf8-plain-text"));
    for t in CONCEALMENT_TYPES {
        types.push(NSString::from_str(t));
    }
    let types = NSArray::from_retained_slice(&types);

    // declareTypes:owner: clears the pasteboard and puts our promise on it;
    // the return value is the new changeCount.
    let change_count: NSInteger =
        unsafe { msg_send![&*pasteboard, declareTypes: &*types, owner: &*provider] };
    if change_count <= 0 {
        return Err("declareTypes:owner: failed".to_string());
    }
    info!("[reliable-paste] published transcript as lazy promise (changeCount {change_count})");

    // Mark injection *before* sending: enigo holds the chord for ~100ms and a
    // fast target may legitimately read while the chord is still held.
    if let Ok(mut st) = state.lock() {
        st.injected_at = Some(Instant::now());
    }
    match send_paste_if_target_unchanged(Some(target.clone())) {
        Ok(true) => {
            info!("[reliable-paste] Cmd+V sent");
            if auto_submit {
                std::thread::sleep(Duration::from_millis(50));
                if let Err(error) =
                    send_return_if_target_unchanged(auto_submit_key, Some(target)).map(|_| ())
                {
                    error!("[reliable-paste] paste succeeded, but auto-submit failed: {error}");
                }
            }
        }
        Ok(false) => {
            if let Ok(mut st) = state.lock() {
                st.injection_failed = true;
            }
            info!("[reliable-paste] target changed before Cmd+V; paste skipped");
        }
        Err(e) => {
            // Keep the transaction alive long enough to replace the promise
            // with plain transcript text. A failed chord never authorizes
            // restoration of the previous clipboard.
            if let Ok(mut st) = state.lock() {
                st.injection_failed = true;
            }
            error!("[reliable-paste] failed to send paste chord: {e}");
        }
    }

    let pending = Arc::new(Mutex::new(MacPending {
        state,
        change_count,
        provider: Some(provider),
        preserve_transcript: clipboard_handling == ClipboardHandling::CopyToClipboard,
        transcript: text.to_string(),
        settled: false,
    }));
    if let Ok(mut slot) = PENDING.lock() {
        *slot = Some(pending.clone());
    }
    spawn_waiter(pending, app_handle.clone());

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn never_restores_prior_clipboard_data() {
        assert_eq!(
            decide_settlement(true, false),
            ClipboardSettlement::ClearClipboard
        );
        assert_eq!(
            decide_settlement(false, false),
            ClipboardSettlement::LeaveUntouched
        );
    }

    #[test]
    fn copy_to_clipboard_always_keeps_transcript() {
        assert_eq!(
            decide_settlement(true, true),
            ClipboardSettlement::KeepTranscript
        );
    }

    #[test]
    fn failed_injection_keeps_transcript_for_recovery() {
        let preserve_transcript = false;
        let injection_failed = true;
        assert_eq!(
            decide_settlement(true, preserve_transcript || injection_failed),
            ClipboardSettlement::KeepTranscript
        );
    }
}
