import Foundation

struct TranscriptionLanguage: Identifiable, Equatable {
    var code: String
    var name: String

    var id: String { code }

    static let all: [TranscriptionLanguage] = [
        TranscriptionLanguage(code: "auto", name: "Auto Detect"),
        TranscriptionLanguage(code: "en", name: "English"),
        TranscriptionLanguage(code: "zh-Hans", name: "Simplified Chinese"),
        TranscriptionLanguage(code: "zh-Hant", name: "Traditional Chinese"),
        TranscriptionLanguage(code: "yue", name: "Cantonese"),
        TranscriptionLanguage(code: "de", name: "German"),
        TranscriptionLanguage(code: "es", name: "Spanish"),
        TranscriptionLanguage(code: "ru", name: "Russian"),
        TranscriptionLanguage(code: "ko", name: "Korean"),
        TranscriptionLanguage(code: "fr", name: "French"),
        TranscriptionLanguage(code: "ja", name: "Japanese"),
        TranscriptionLanguage(code: "pt", name: "Portuguese"),
        TranscriptionLanguage(code: "tr", name: "Turkish"),
        TranscriptionLanguage(code: "pl", name: "Polish"),
        TranscriptionLanguage(code: "ca", name: "Catalan"),
        TranscriptionLanguage(code: "nl", name: "Dutch"),
        TranscriptionLanguage(code: "ar", name: "Arabic"),
        TranscriptionLanguage(code: "sv", name: "Swedish"),
        TranscriptionLanguage(code: "it", name: "Italian"),
        TranscriptionLanguage(code: "id", name: "Indonesian"),
        TranscriptionLanguage(code: "hi", name: "Hindi"),
        TranscriptionLanguage(code: "fi", name: "Finnish"),
        TranscriptionLanguage(code: "vi", name: "Vietnamese"),
        TranscriptionLanguage(code: "he", name: "Hebrew"),
        TranscriptionLanguage(code: "uk", name: "Ukrainian"),
        TranscriptionLanguage(code: "el", name: "Greek"),
        TranscriptionLanguage(code: "ms", name: "Malay"),
        TranscriptionLanguage(code: "cs", name: "Czech"),
        TranscriptionLanguage(code: "ro", name: "Romanian"),
        TranscriptionLanguage(code: "da", name: "Danish"),
        TranscriptionLanguage(code: "hu", name: "Hungarian"),
        TranscriptionLanguage(code: "ta", name: "Tamil"),
        TranscriptionLanguage(code: "no", name: "Norwegian"),
        TranscriptionLanguage(code: "th", name: "Thai"),
        TranscriptionLanguage(code: "ur", name: "Urdu"),
        TranscriptionLanguage(code: "hr", name: "Croatian"),
        TranscriptionLanguage(code: "bg", name: "Bulgarian"),
        TranscriptionLanguage(code: "lt", name: "Lithuanian"),
        TranscriptionLanguage(code: "la", name: "Latin"),
        TranscriptionLanguage(code: "mi", name: "Maori"),
        TranscriptionLanguage(code: "ml", name: "Malayalam"),
        TranscriptionLanguage(code: "cy", name: "Welsh"),
        TranscriptionLanguage(code: "sk", name: "Slovak"),
        TranscriptionLanguage(code: "te", name: "Telugu"),
        TranscriptionLanguage(code: "fa", name: "Persian"),
        TranscriptionLanguage(code: "lv", name: "Latvian"),
        TranscriptionLanguage(code: "bn", name: "Bengali"),
        TranscriptionLanguage(code: "sr", name: "Serbian"),
        TranscriptionLanguage(code: "az", name: "Azerbaijani"),
        TranscriptionLanguage(code: "sl", name: "Slovenian"),
        TranscriptionLanguage(code: "kn", name: "Kannada"),
        TranscriptionLanguage(code: "et", name: "Estonian"),
        TranscriptionLanguage(code: "mk", name: "Macedonian"),
        TranscriptionLanguage(code: "br", name: "Breton"),
        TranscriptionLanguage(code: "eu", name: "Basque"),
        TranscriptionLanguage(code: "is", name: "Icelandic"),
        TranscriptionLanguage(code: "hy", name: "Armenian"),
        TranscriptionLanguage(code: "ne", name: "Nepali"),
        TranscriptionLanguage(code: "mn", name: "Mongolian"),
        TranscriptionLanguage(code: "bs", name: "Bosnian"),
        TranscriptionLanguage(code: "kk", name: "Kazakh"),
        TranscriptionLanguage(code: "sq", name: "Albanian"),
        TranscriptionLanguage(code: "sw", name: "Swahili"),
        TranscriptionLanguage(code: "gl", name: "Galician"),
        TranscriptionLanguage(code: "mr", name: "Marathi"),
        TranscriptionLanguage(code: "pa", name: "Punjabi"),
        TranscriptionLanguage(code: "si", name: "Sinhala"),
        TranscriptionLanguage(code: "km", name: "Khmer"),
        TranscriptionLanguage(code: "sn", name: "Shona"),
        TranscriptionLanguage(code: "yo", name: "Yoruba"),
        TranscriptionLanguage(code: "so", name: "Somali"),
        TranscriptionLanguage(code: "af", name: "Afrikaans"),
        TranscriptionLanguage(code: "oc", name: "Occitan"),
        TranscriptionLanguage(code: "ka", name: "Georgian"),
        TranscriptionLanguage(code: "be", name: "Belarusian"),
        TranscriptionLanguage(code: "tg", name: "Tajik"),
        TranscriptionLanguage(code: "sd", name: "Sindhi"),
        TranscriptionLanguage(code: "gu", name: "Gujarati"),
        TranscriptionLanguage(code: "am", name: "Amharic"),
        TranscriptionLanguage(code: "yi", name: "Yiddish"),
        TranscriptionLanguage(code: "lo", name: "Lao"),
        TranscriptionLanguage(code: "uz", name: "Uzbek"),
        TranscriptionLanguage(code: "fo", name: "Faroese"),
        TranscriptionLanguage(code: "ht", name: "Haitian Creole"),
        TranscriptionLanguage(code: "ps", name: "Pashto"),
        TranscriptionLanguage(code: "tk", name: "Turkmen"),
        TranscriptionLanguage(code: "nn", name: "Nynorsk"),
        TranscriptionLanguage(code: "mt", name: "Maltese"),
        TranscriptionLanguage(code: "sa", name: "Sanskrit"),
        TranscriptionLanguage(code: "lb", name: "Luxembourgish"),
        TranscriptionLanguage(code: "my", name: "Myanmar"),
        TranscriptionLanguage(code: "bo", name: "Tibetan"),
        TranscriptionLanguage(code: "tl", name: "Tagalog"),
        TranscriptionLanguage(code: "mg", name: "Malagasy"),
        TranscriptionLanguage(code: "as", name: "Assamese"),
        TranscriptionLanguage(code: "tt", name: "Tatar"),
        TranscriptionLanguage(code: "haw", name: "Hawaiian"),
        TranscriptionLanguage(code: "ln", name: "Lingala"),
        TranscriptionLanguage(code: "ha", name: "Hausa"),
        TranscriptionLanguage(code: "ba", name: "Bashkir"),
        TranscriptionLanguage(code: "jw", name: "Javanese"),
        TranscriptionLanguage(code: "su", name: "Sundanese"),
    ]

    static func displayName(for code: String) -> String {
        all.first { $0.code == code }?.name ?? code
    }

    static func isKnown(_ code: String) -> Bool {
        all.contains { $0.code == code }
    }
}
