name: "Build Test"

on: workflow_dispatch

jobs:
  build-test:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-26" # for Arm based Macs (M1 and above).
            args: "--target aarch64-apple-darwin"
            target: "aarch64-apple-darwin"
          - platform: "macos-latest" # for Intel based macs.
            args: "--target x86_64-apple-darwin"
            target: "x86_64-apple-darwin"

    uses: ./.github/workflows/build.yml
    with:
      platform: ${{ matrix.platform }}
      target: ${{ matrix.target }}
      build-args: ${{ matrix.args }}
      sign-binaries: false
      asset-prefix: "murmur-test-unsigned-not-notarized"
      upload-artifacts: true
      ref: ${{ github.sha }}
